# Generated by Django 4.2.5 on 2023-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='', max_length=100000, null=True, upload_to=''),
        ),
    ]
