# Generated by Django 4.2.5 on 2023-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
