# Generated by Django 4.2.5 on 2023-10-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_image',
            new_name='image',
        ),
    ]
