# Generated by Django 4.2.7 on 2023-11-27 11:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='division',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_big',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sidemenu',
            name='query',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sidemenu',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(max_length=10000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offered_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='side_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='global_computer_api.sidemenu'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sidemenu',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='mid_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='mini_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SubSideMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('side_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_side_menu', to='global_computer_api.sidemenu')),
            ],
        ),
    ]
