# Generated by Django 4.2.4 on 2023-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0006_alter_product_offered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offered_time',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
