# Generated by Django 4.2.4 on 2023-09-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0007_alter_product_offered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offered_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
