# Generated by Django 4.2.4 on 2023-09-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0008_alter_product_offered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='side_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='global_computer_api.sidemenu'),
        ),
    ]
