# Generated by Django 4.2.4 on 2023-09-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0009_alter_product_side_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='color',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='mid_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='mini_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
