# Generated by Django 4.2.4 on 2023-09-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0010_alter_slider_color_alter_slider_mid_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='color',
            field=models.BooleanField(default=False),
        ),
    ]
