# Generated by Django 4.2.4 on 2023-09-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0012_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
