# Generated by Django 4.2.5 on 2023-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0017_remove_brand_logo_alter_brand_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemenu',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
