# Generated by Django 4.2.5 on 2023-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0018_sidemenu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sidemenu',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
