# Generated by Django 4.2.5 on 2023-09-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0022_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
