# Generated by Django 4.2.5 on 2023-09-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0023_rename_slug_category_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
