# Generated by Django 4.2.5 on 2023-09-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0025_reviews_avg_star_reviews_total_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='avg_star',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
