# Generated by Django 4.2.5 on 2023-09-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0026_alter_reviews_avg_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='total_review',
        ),
    ]
