# Generated by Django 4.2.5 on 2023-09-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0028_reviews_total_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='avg_star',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='total_review',
        ),
    ]
