# Generated by Django 4.2.5 on 2023-10-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0029_remove_reviews_avg_star_remove_reviews_total_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemenu',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
