# Generated by Django 4.2.5 on 2023-10-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0032_order_district_order_division_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(null=True),
        ),
    ]
