# Generated by Django 4.2.5 on 2023-10-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0034_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
