# Generated by Django 4.2.5 on 2023-10-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0035_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidemenu',
            name='query',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SubSideMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('side_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_computer_api.sidemenu')),
            ],
        ),
    ]
