# Generated by Django 4.2.5 on 2023-10-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0036_sidemenu_query_subsidemenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidemenu',
            name='side_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_side_menu', to='global_computer_api.sidemenu'),
        ),
    ]
