# Generated by Django 4.2.5 on 2023-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0037_alter_subsidemenu_side_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidemenu',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
