# Generated by Django 4.2.5 on 2023-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0038_alter_subsidemenu_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(max_length=10000, null=True, upload_to=''),
        ),
    ]
