# Generated by Django 4.2.7 on 2023-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0054_alter_reviews_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_big',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
    ]
