name: Django CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 
    runs-on: self-hosted

    steps: 
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install Dependencies
        run: |
          cd Server/global_computer
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          pip install mysqlclient
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py collectstatic
          
        env: 
          NAME: ${{ vars.NAME }}
          USER: ${{ vars.USER }}
          PASSWORD: ${{ vars.PASSWORD }}
          HOST: ${{ vars.HOST }}
          PORT: ${{ vars.PORT }}
          DEBUG_PRODUCTION: ${{ vars.DEBUG_PRODUCTION }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          

