name: Django CI CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependency
        run: |
          cd Server/global_computer 
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt mysqlclient
          python manage.py makemigrations
          python manage.py migrate
          python manage.py migrate --run-syncdb
          sudo service gunicorn restart
          sudo service nginx restart

      