name: Django CI CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependency
        run: |
          cd Server/global_computer 
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt mysqlclient
          python manage.py makemigrations
          python manage.py migrate --run-syncdb
          sudo service gunicorn restart
          sudo service nginx restart
        env:
          NAME: "global_ecom" 
          USER: "jahidul"
          PASSWORD: "J@hidul42598475"
          HOST: "localhost"
          PORT: "3306"
          DEBUG: "False"
          DJANGO_SECRET_KEY: "django-insecure-wpx$@io&-dzyks&m=z%&uc=4b!qn*@6no$(^a(!qivf2jypr#z"
      