name: Django CI CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.11
        uses: actions/setup-python@v3
        with: 
          python-version: 3
      - name: Install Dependency
        run: |
          cd Server/global_computer 
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt mysqlclient
        env:
          NAME: "global_ecom" 
          USER: "jahidul"
          PASSWORD: "J@hidul42598475"
          HOST: "localhost"
          PORT: "3306"
          DEBUG: "True"
          DJANGO_SECRET_KEY: "django-insecure-wpx$@io&-dzyks&m=z%&uc=4b!qn*@6no$(^a(!qivf2jypr#z"
      