name: Django CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 
    runs-on: self-hosted

    steps: 
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          cd Server/global_computer
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          pip install mysqlclient
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py collectstatic
        env: 
          NAME: "global_ecom"
          USER: "jahidul"
          PASSWORD: "J@hidul42598475"
          HOST: "localhost"
          PORT: "3306"
          

