name: Django CI CD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      
      - uses: actions/checkout@v4
      - name: Install Dependency
        run: |
          cd Server/global_computer 
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt mysqlclient
          python manage.py makemigrations
          python manage.py migrate
          sudo service gunicorn restart
          sudo service nginx restart
        env:
          NAME: ${{ vars.NAME }}
          PASSWORD: ${{ vars.PASSWORD }}
          HOST: ${{ vars.HOST }}
          POST: ${{ vars.POST }}
          USER: ${{ vars.USER }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: ${{ vars.DEBUG }}

      - name: Copy media file from backup
        run: |
          cp -r /home/jahidul/glc-ecom/Server/global_computer/media /home/jahidul/glc-ecom/Server/global_computer_api/media
          


      